Repository kubesphere-sigs/ks-devops-helm-chart, pull requests merged in 2021-12, with the labels that each got.

#43 Move migrate job into init containers of devops apiserver
  charts/ks-devops/templates/config-migrate-job.yaml
  charts/ks-devops/templates/deployment-apiserver.yaml
Labels: size/S, lgtm, approved

#44 Bump up ks-devops charts for next release
  charts/ks-devops/Chart.yaml
Labels: lgtm, size/XS, approved

#45 Set the default jenkins image tag as master
  charts/ks-devops/charts/jenkins/values.yaml
Labels: lgtm, size/XS, approved

#20 Convert GC logging Flags to xlog
  charts/ks-devops/charts/jenkins/values.yaml
Labels: hold, lgtm, approved

#46 Avoid print too many gc log output
  charts/ks-devops/charts/jenkins/README.md
  charts/ks-devops/charts/jenkins/values.yaml
Labels: size/S, lgtm, approved

#47 Correct wrong image configuration on python agent
  charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
Labels: lgtm, size/XS, approved

#48 Bump jenkins jnlp agent from 3.27 to 4.10
  charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
  charts/ks-devops/charts/jenkins/values.yaml
Labels: size/S, lgtm, approved

#39 add new devops agent for jdk11
  charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
  charts/ks-devops/charts/jenkins/values.yaml
Labels: hacktoberfest-accepted, size/S, lgtm, approved

#51 Override the default namespace of jwt cmd in the controller
  .gitignore
  charts/ks-devops/templates/deployment-controller.yaml
Labels: lgtm, size/XS, approved
