Repository kubesphere-sigs/ks-devops-helm-chart, pull requests merged in 2021-11, with the labels that each got.

#34 Upgrade versions of dependencies for v3.2.0
  charts/ks-devops/charts/jenkins/values.yaml
  charts/ks-devops/charts/s2i/values.yaml
Labels: size/S, lgtm

#33 Bump chart version to 0.1.6
  charts/ks-devops/Chart.yaml
  charts/ks-devops/charts/jenkins/Chart.yaml
  charts/ks-devops/charts/s2i/Chart.yaml
Labels: chore, size/S, lgtm

#36 Fix the sub-chart version issues
  charts/ks-devops/Chart.yaml
Labels: lgtm, size/XS

#37 Use the same image tag for the s2i images
  charts/ks-devops/Chart.yaml
  charts/ks-devops/charts/s2i/Chart.yaml
  charts/ks-devops/charts/s2i/values.yaml
Labels: lgtm, size/M

#38 Bump jenkins image tag to 3.2.0-2.249.1
  charts/ks-devops/Chart.yaml
  charts/ks-devops/charts/jenkins/Chart.yaml
  charts/ks-devops/charts/jenkins/values.yaml
Labels: lgtm, size/XS

#31 Reformat yaml config item in pod template
  charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
Labels: lgtm

#30 Add new Devops agent for Python
  charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
  charts/ks-devops/charts/jenkins/values.yaml
Labels: hacktoberfest-accepted, lgtm, size/M

#40 Add a badge for the download number
  README.md
Labels: lgtm, size/XS

#42 Create OWNERS file
  OWNERS
Labels: size/XS

#41 Adjust default xmx/xms configuration at jenkins-values.yaml
  charts/ks-devops/charts/jenkins/values.yaml
Labels: lgtm, size/XS, approved
