Repository kubesphere-sigs/ks-devops-helm-chart, pull requests merged in 2022-03, with the labels that each got.

#61 Add the CRD of the application
  Makefile
  charts/ks-devops/crds/gitops.kubesphere.io_applications.yaml
  hack/fetch-crds.sh
Labels: lgtm, size/L, approved

#63 Re-sync template CRDs
  charts/ks-devops/crds/devops.kubesphere.io_clustertemplates.yaml
  charts/ks-devops/crds/devops.kubesphere.io_templates.yaml
Labels: lgtm, size/XS, approved

#64 Fetch cluster templates from kubesphere-sigs/pipeline-templates
  Makefile
  charts/ks-devops/templates/golang.yaml
  charts/ks-devops/templates/nodejs.yaml
  hack/fetch-templates.sh
Labels: lgtm, size/L, approved

#66 Rename cluster template files and deprecated ci and cicd templates
  charts/ks-devops/templates/cluster-template-ci.yaml
  charts/ks-devops/templates/cluster-template-cicd.yaml
  charts/ks-devops/templates/cluster-template-golang.yaml
  charts/ks-devops/templates/cluster-template-maven.yaml
  charts/ks-devops/templates/cluster-template-nodejs.yaml
  hack/fetch-templates.sh
Labels: size/L

#65 Update CRDs using fetch-crds.sh
  charts/ks-devops/crds/gitops.kubesphere.io_applications.yaml
Labels: lgtm, approved, size/XXL

#67 Update the clusterrole setting of the devops
  charts/ks-devops/templates/serviceaccount.yaml
Labels: lgtm, size/L, approved
