Repository kubesphere-sigs/ks-devops-helm-chart, pull requests merged in 2022-12, with the labels that each got.

#84 update value of containerCapStr
  charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
Labels: lgtm, size/XS, approved

#86 Revert "release 0.1.16"
  charts/ks-devops/Chart.yaml
Labels: size/XS, approved

#87 release 0.1.16
  charts/ks-devops/Chart.yaml
Labels: size/XS, approved

#88 release 0.1.17
  charts/ks-devops/Chart.yaml
Labels: approved
