Repository kubesphere-sigs/ks-devops-helm-chart, pull requests merged in 2022-02, with the labels that each got.

#54 Fetch templates.devops.kubesphere.io CRD
  charts/ks-devops/charts/s2i/crds/devops.kubesphere.io_s2ibuildertemplates.yaml
  charts/ks-devops/crds/devops.kubesphere.io_pipelineruns.yaml
  charts/ks-devops/crds/devops.kubesphere.io_pipelines.yaml
  charts/ks-devops/crds/devops.kubesphere.io_templates.yaml
  hack/fetch-crds.sh
Labels: lgtm, size/L, approved

#55 Update the CRD of the DevOpsProject
  charts/ks-devops/crds/devops.kubesphere.io_devopsprojects.yaml
  hack/fetch-crds.sh
Labels: lgtm, size/L, approved

#56 Fetch clustertemplates.devops.kubesphere.io CRD
  charts/ks-devops/crds/devops.kubesphere.io_clustertemplates.yaml
  hack/fetch-crds.sh
Labels: lgtm, size/L, approved

#58 Prepend 'http://' for 'unclassified.location.url' in CasC configuration
  charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
Labels: lgtm, size/XS, approved

#57 Add pre-defined templates
  charts/ks-devops/templates/cluster-template-ci.yaml
  charts/ks-devops/templates/cluster-template-cicd.yaml
Labels: lgtm, size/L, approved

#59 Update Template and ClusterTemplate CRDs
  charts/ks-devops/crds/devops.kubesphere.io_clustertemplates.yaml
  charts/ks-devops/crds/devops.kubesphere.io_templates.yaml
  charts/ks-devops/templates/cluster-template-ci.yaml
  charts/ks-devops/templates/cluster-template-cicd.yaml
Labels: size/XS, approved

#60 Typo fix: discription to description
  charts/ks-devops/templates/cluster-template-ci.yaml
Labels: lgtm, size/XS, approved
