Repository kubesphere-sigs/ks-devops-helm-chart, pull requests merged in 2023-09, with the labels that each got.

#119 Add casc annotation and upgrade to v3.5.0
  charts/ks-devops/Chart.yaml
  charts/ks-devops/charts/jenkins/Chart.yaml
  charts/ks-devops/charts/jenkins/templates/alerting-clusterrulegroup.yaml
  charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
  charts/ks-devops/charts/jenkins/values.yaml
Labels: lgtm, size/M, approved

#120 Add build user var step
  charts/ks-devops/templates/cluster-step-templates.yaml
Labels: size/S, lgtm, approved

#121 remove un-used args of gc pipelineruns in project
  charts/ks-devops/templates/cronjob-gc.yaml
Labels: lgtm, size/XS, approved

#122 bugfix: setup cronjob apiversion failed
  charts/ks-devops/templates/_helpers.tpl
  charts/ks-devops/templates/cronjob-gc.yaml
Labels: size/S, lgtm, approved

#123 update chart version to 0.3.1
  charts/ks-devops/Chart.yaml
Labels: lgtm, size/XS, approved
