Repository kubesphere-sigs/ks-devops-helm-chart, pull requests merged in 2023-03, with the labels that each got.

#98 DEBUG: Remove something as jenkins.enable==fasle
  charts/ks-devops/templates/NOTES.txt
  charts/ks-devops/templates/config.yaml
Labels: size/S, lgtm, approved

#100 Add step templates
  charts/ks-devops/crds/devops.kubesphere.io_clustersteptemplates.yaml
  charts/ks-devops/templates/cluster-step-templates.yaml
  charts/ks-devops/templates/cluster-template-golang.yaml
  charts/ks-devops/templates/cluster-template-maven.yaml
  charts/ks-devops/templates/cluster-template-nodejs.yaml
  charts/ks-devops/templates/cronjob-gc.yaml
Labels: lgtm, approved, size/XXL

#97 upgrade jenkins chart & release 0.1.20
  charts/ks-devops/Chart.yaml
  charts/ks-devops/charts/jenkins/Chart.yaml
Labels: size/S, approved

#103 bugfix: CronJob apiVersion:batch/v1 is not compatible with k8s-1.20
  charts/ks-devops/templates/_helpers.tpl
  charts/ks-devops/templates/cronjob-gc.yaml
Labels: size/S, lgtm, approved

#107 Add argocd enable to true for apiserver
  charts/ks-devops/templates/deployment-apiserver.yaml
Labels: lgtm, size/XS, approved
